drop user C00001 cascade;

drop role customer;

--CREATES ROLES 
CREATE ROLE CUSTOMER;
CREATE ROLE MANAGER;
CREATE ROLE DELIVERY_PERSON;


-- Customer
-- grant permission to views
-------------------------------
/
GRANT SELECT ON  DELIVERY_DETAILS_VIEW TO CUSTOMER;
/
GRANT SELECT ON  CUSTOMER_CHOICE_BY_SEASON_VIEW TO CUSTOMER;

--select * from DELIVERY_DETAILS_VIEW


-- DELIVERY_PERSON
-- grant permission to views
-------------------------------
/
GRANT SELECT ON  DELIVERY_SCHEDULE_VIEW TO DELIVERY_PERSON;
/
GRANT SELECT ON  DELIVERY_DETAILS_VIEW TO DELIVERY_PERSON;
/

-- Manager
--grant permission to views

GRANT SELECT ON  POPULAR_MEAL_BY_SUBSCRIPTION_VIEW TO MANAGER;
/
GRANT SELECT ON REVENUE_VIEW TO MANAGER;
/

-----------------------------------------------------
--
--create user C00001 identified by Welcome_123456789;
--GRANT CREATE SESSION TO C00001;
--GRANT UNLIMITED TABLESPACE TO C00001;


--- Grant roles for users
----------------------------------------------------
GRANT MANAGER TO MGR00001;
/
GRANT MANAGER TO MGR00002;
/
GRANT MANAGER TO MGR00003;
/
GRANT MANAGER TO MGR00004;

----------------------------------

GRANT CUSTOMER TO C00001;
/
GRANT CUSTOMER TO C00002;
/
GRANT CUSTOMER TO C00003;
/
GRANT CUSTOMER TO C00004;
------------------------------

GRANT DELIVERY_PERSON TO DP00001;
/
GRANT DELIVERY_PERSON TO DP00002;
/
GRANT DELIVERY_PERSON TO DP00003;
/
GRANT DELIVERY_PERSON TO DP00004;
/
--------------------------------------